# -*- coding: utf-8 -*-
"""M25CSA036_prob4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17kSTwYNwk8icpEUxy5QKPnTxeb5euhp6
"""

!unzip bbc_sport_politics.zip

# Commented out IPython magic to ensure Python compatibility.
# %%writefile M25CSA036_prob4.py
# # ------------------------------------------------------------
# # CSL 7640 : Natural Language Understanding
# # Assignment 1 - Problem 4
# # Sports vs Politics Classification (Robustness Evaluation)
# # Roll Number: M25CSA036
# # ------------------------------------------------------------
# 
# import os
# import random
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.model_selection import train_test_split
# from sklearn.naive_bayes import MultinomialNB
# from sklearn.linear_model import LogisticRegression
# from sklearn.svm import LinearSVC
# from sklearn.metrics import accuracy_score, classification_report
# 
# 
# def add_heavy_noise(text, drop_prob=0.3):
#     words = text.split()
#     noisy_words = [w for w in words if random.random() > drop_prob]
#     return " ".join(noisy_words)
# 
# 
# def load_dataset():
#     texts = []
#     labels = []
# 
#     for filename in os.listdir("sport"):
#         with open(os.path.join("sport", filename), "r", encoding="latin-1") as f:
#             texts.append(add_heavy_noise(f.read()))
#             labels.append("sport")
# 
#     for filename in os.listdir("politics"):
#         with open(os.path.join("politics", filename), "r", encoding="latin-1") as f:
#             texts.append(add_heavy_noise(f.read()))
#             labels.append("politics")
# 
#     return texts, labels
# 
# 
# def main():
#     print("Loading BBC News dataset (robustness setup)...")
#     X, y = load_dataset()
# 
#     # Much smaller training set
#     X_train, X_test, y_train, y_test = train_test_split(
#         X, y,
#         train_size=0.6,
#         random_state=11
#     )
# 
#     vectorizer = TfidfVectorizer(
#         ngram_range=(1, 1),     # only unigrams
#         max_features=2000      # aggressive feature reduction
#     )
# 
#     X_train_vec = vectorizer.fit_transform(X_train)
#     X_test_vec = vectorizer.transform(X_test)
# 
#     models = {
#         "Multinomial Naive Bayes": MultinomialNB(),
#         "Logistic Regression": LogisticRegression(max_iter=300),
#         "Linear SVM": LinearSVC()
#     }
# 
#     for name, model in models.items():
#         print("\n==============================")
#         print("Model:", name)
# 
#         model.fit(X_train_vec, y_train)
#         preds = model.predict(X_test_vec)
# 
#         print("Accuracy:", accuracy_score(y_test, preds))
#         print(classification_report(y_test, preds))
# 
# 
# if __name__ == "__main__":
#     main()
#

!python M25CSA036_prob4.py